services:
  - type: web
    name: supermarket-backend
    plan: free
    env: node
    rootDir: server
    buildCommand: npm install && npx prisma generate && npx prisma db push && npm run build
    startCommand: npm start
    envVars:
      - key: DATABASE_URL
        value: "file:./supermarket.db"
      - key: JWT_SECRET
        value: "shoppos-secret-key-2024"

  - type: web
    name: supermarket-frontend
    env: static
    rootDir: client
    buildCommand: echo "Using pre-built dist"
    staticPublishPath: dist
